# Project: Projet_C
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = Analyse_syntaxique/source/analyse_syntaxique.o Analyse_syntaxique/source/lexeme.o Analyse_syntaxique/source/test_analyse_syntaxique.o
LINKOBJ  = Analyse_syntaxique/source/analyse_syntaxique.o Analyse_syntaxique/source/lexeme.o Analyse_syntaxique/source/test_analyse_syntaxique.o
LIBS     = -L"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib32" -L"D:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -g3
INCS     = -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Projet_C_Myrias.exe
CXXFLAGS = $(CXXINCS) -m32 -g3 -g --std=c++11  -llstdc++
CFLAGS   = $(INCS) -m32 -g3 -g --std=c++11  -llstdc++
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Analyse_syntaxique/source/analyse_syntaxique.o: Analyse_syntaxique/source/analyse_syntaxique.cc
	$(CPP) -c Analyse_syntaxique/source/analyse_syntaxique.cc -o Analyse_syntaxique/source/analyse_syntaxique.o $(CXXFLAGS)

Analyse_syntaxique/source/lexeme.o: Analyse_syntaxique/source/lexeme.cc
	$(CPP) -c Analyse_syntaxique/source/lexeme.cc -o Analyse_syntaxique/source/lexeme.o $(CXXFLAGS)

Analyse_syntaxique/source/test_analyse_syntaxique.o: Analyse_syntaxique/source/test_analyse_syntaxique.cc
	$(CPP) -c Analyse_syntaxique/source/test_analyse_syntaxique.cc -o Analyse_syntaxique/source/test_analyse_syntaxique.o $(CXXFLAGS)
